#!/bin/bash

# Test JSON syntax highlighting feature
# This script sets up a test endpoint and verifies JSON highlighting works

echo "Testing JSON Syntax Highlighting"
echo "================================="
echo ""
echo "Steps to test:"
echo "1. Run the application: cargo run --release"
echo "2. Create a new collection (press 'n' in Collections panel)"
echo "3. Create a new endpoint with these settings:"
echo "   - Name: JSON Test"
echo "   - Method: GET"
echo "   - URL: https://jsonplaceholder.typicode.com/users/1"
echo "4. Execute the request (press 'e')"
echo "5. Look for '🎨 JSON' indicator in the response title"
echo "6. Verify colors:"
echo "   - Braces {} should be colored (cyan, yellow, etc.)"
echo "   - Keys should be light blue"
echo "   - String values should be green"
echo "   - Numbers should be magenta"
echo "7. Press 't' to toggle network traffic"
echo "8. Verify JSON highlighting still works with traffic displayed"
echo ""
echo "Expected JSON response structure:"
echo "{"
echo "  \"id\": 1,"
echo "  \"name\": \"Leanne Graham\","
echo "  \"username\": \"Bret\","
echo "  \"email\": \"Sincere@april.biz\","
echo "  ..."
echo "}"
echo ""
echo "If you see '🎨 JSON' in the title and colors in the response,"
echo "the feature is working correctly!"
