#!/bin/bash

# Test script for timeline charts feature

echo "Timeline Charts Feature - Test Plan"
echo "===================================="
echo ""
echo "This feature adds real-time sparkline charts to the load test screen."
echo ""
echo "Test Steps:"
echo "----------"
echo ""
echo "1. Start the application:"
echo "   cargo run"
echo ""
echo "2. Create a test endpoint (if not exists):"
echo "   - Press 'n' to create collection"
echo "   - Name: 'Test Collection'"
echo "   - Press 'n' again for endpoint"
echo "   - Name: 'JSONPlaceholder API'"
echo "   - URL: 'https://jsonplaceholder.typicode.com/users/1'"
echo ""
echo "3. Start a load test:"
echo "   - Select the endpoint"
echo "   - Press 'l' for load test"
echo "   - Configure: 20 workers, 60 seconds, 10s ramp-up"
echo "   - Press Enter to start"
echo ""
echo "4. Observe the charts:"
echo "   - Wait 5 seconds for first data point"
echo "   - Charts should appear on the right side"
echo "   - Two sparklines: p95 Latency and RPS"
echo ""
echo "5. Verify chart behavior:"
echo "   - Charts update every 5 seconds"
echo "   - p95 latency shows trend (green/yellow/red)"
echo "   - RPS chart shows request rate trend (cyan)"
echo "   - Charts show last 60 seconds (12 points max)"
echo ""
echo "6. Check color coding:"
echo "   - p95 < 100ms: Green (good)"
echo "   - p95 100-200ms: Yellow (warning)"
echo "   - p95 > 200ms: Red (critical)"
echo ""
echo "Expected Results:"
echo "================"
echo "✓ Charts appear after 5 seconds"
echo "✓ p95 latency sparkline shows on top right"
echo "✓ RPS sparkline shows below p95"
echo "✓ Charts update every 5 seconds"
echo "✓ Color changes based on latency thresholds"
echo "✓ Statistics remain on left side"
echo "✓ Bar chart remains at bottom (unchanged)"
echo "✓ No performance degradation"
echo ""
echo "To run: cd rest-api-tui && cargo run"
