#!/bin/bash

# Test script to verify load test configuration form works
# This script documents the expected behavior

echo "Load Test Configuration Form - Test Plan"
echo "=========================================="
echo ""
echo "1. Start the application: cargo run"
echo ""
echo "2. Create a test collection and endpoint:"
echo "   - Press 'n' to create new collection"
echo "   - Enter name: 'Test Collection'"
echo "   - Press Enter to save"
echo "   - Press 'n' again to create new endpoint"
echo "   - Enter name: 'Test API'"
echo "   - Tab to URL field"
echo "   - Enter URL: 'https://jsonplaceholder.typicode.com/users/1'"
echo "   - Press Enter to save"
echo ""
echo "3. Test Load Test Configuration Form:"
echo "   - Select the endpoint"
echo "   - Press 'l' to start load test"
echo "   - Configuration form should appear"
echo ""
echo "4. Test Character Input:"
echo "   - Type '20' in Concurrency field (should accept digits)"
echo "   - Press Tab to move to Duration field"
echo "   - Type '60' in Duration field"
echo "   - Press Tab to move to Ramp-up field"
echo "   - Type '10' in Ramp-up field"
echo "   - Press Shift+Tab to go back to Duration field"
echo ""
echo "5. Test Backspace:"
echo "   - Press Backspace to delete characters"
echo "   - Verify characters are removed from current field"
echo ""
echo "6. Test Preview:"
echo "   - Verify preview shows: '20 workers will execute requests for 60 seconds'"
echo "   - Verify preview shows: 'Load will ramp up over 10 seconds'"
echo ""
echo "7. Start Load Test:"
echo "   - Press Enter to start the load test"
echo "   - Verify load test starts with configured parameters"
echo "   - Verify RPS updates during test (should show ~20)"
echo "   - Verify percentile metrics are displayed:"
echo "     * Avg latency"
echo "     * p50 (median)"
echo "     * p90"
echo "     * p95"
echo "     * p99"
echo "     * Max latency"
echo ""
echo "8. Stop Load Test:"
echo "   - Press Esc to stop the test early"
echo "   - Verify test stops and returns to main screen"
echo ""
echo "Expected Results:"
echo "================="
echo "✓ Configuration form accepts numeric input"
echo "✓ Tab cycles through fields (concurrency -> duration -> ramp_up -> concurrency)"
echo "✓ Shift+Tab cycles backwards"
echo "✓ Backspace deletes characters"
echo "✓ Preview updates as you type"
echo "✓ Enter starts load test with configured parameters"
echo "✓ RPS updates every 500ms during test (no longer stuck at 0)"
echo "✓ Percentile metrics (avg, p50, p90, p95, p99, max) are displayed"
echo "✓ Workers ramp up gradually over ramp-up period"
echo "✓ Esc stops the test"
echo ""
echo "To run the app: cd rest-api-tui && cargo run"
